sudo: required
language: generic
services:
- docker
script:
- sh build.sh
if: tag IS blank
env:
  jobs:
    - DEBIAN=stretch-backports TAG=1.14.1 SOURCE=1.14.1-1~bpo9+1
    - DEBIAN=buster TAG=1.14.2 SOURCE=1.14.2-2+deb10u1
